package com.itoystergold.pojo;

import java.util.Date;

public class Vipuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vid
     *
     * @mbg.generated
     */
    private String vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.parentId
     *
     * @mbg.generated
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vname
     *
     * @mbg.generated
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vusername
     *
     * @mbg.generated
     */
    private String vusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vtelephone
     *
     * @mbg.generated
     */
    private String vtelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vlevel
     *
     * @mbg.generated
     */
    private String vlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vpassword
     *
     * @mbg.generated
     */
    private String vpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vcode
     *
     * @mbg.generated
     */
    private String vcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.vstatus
     *
     * @mbg.generated
     */
    private String vstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipuser.is_parent
     *
     * @mbg.generated
     */
    private String isParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vid
     *
     * @return the value of vipuser.vid
     *
     * @mbg.generated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vid
     *
     * @param vid the value for vipuser.vid
     *
     * @mbg.generated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.parentId
     *
     * @return the value of vipuser.parentId
     *
     * @mbg.generated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.parentId
     *
     * @param parentid the value for vipuser.parentId
     *
     * @mbg.generated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vname
     *
     * @return the value of vipuser.vname
     *
     * @mbg.generated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vname
     *
     * @param vname the value for vipuser.vname
     *
     * @mbg.generated
     */
    public void setVname(String vname) {
        this.vname = vname == null ? null : vname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vusername
     *
     * @return the value of vipuser.vusername
     *
     * @mbg.generated
     */
    public String getVusername() {
        return vusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vusername
     *
     * @param vusername the value for vipuser.vusername
     *
     * @mbg.generated
     */
    public void setVusername(String vusername) {
        this.vusername = vusername == null ? null : vusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vtelephone
     *
     * @return the value of vipuser.vtelephone
     *
     * @mbg.generated
     */
    public String getVtelephone() {
        return vtelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vtelephone
     *
     * @param vtelephone the value for vipuser.vtelephone
     *
     * @mbg.generated
     */
    public void setVtelephone(String vtelephone) {
        this.vtelephone = vtelephone == null ? null : vtelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vlevel
     *
     * @return the value of vipuser.vlevel
     *
     * @mbg.generated
     */
    public String getVlevel() {
        return vlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vlevel
     *
     * @param vlevel the value for vipuser.vlevel
     *
     * @mbg.generated
     */
    public void setVlevel(String vlevel) {
        this.vlevel = vlevel == null ? null : vlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vpassword
     *
     * @return the value of vipuser.vpassword
     *
     * @mbg.generated
     */
    public String getVpassword() {
        return vpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vpassword
     *
     * @param vpassword the value for vipuser.vpassword
     *
     * @mbg.generated
     */
    public void setVpassword(String vpassword) {
        this.vpassword = vpassword == null ? null : vpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vcode
     *
     * @return the value of vipuser.vcode
     *
     * @mbg.generated
     */
    public String getVcode() {
        return vcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vcode
     *
     * @param vcode the value for vipuser.vcode
     *
     * @mbg.generated
     */
    public void setVcode(String vcode) {
        this.vcode = vcode == null ? null : vcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.vstatus
     *
     * @return the value of vipuser.vstatus
     *
     * @mbg.generated
     */
    public String getVstatus() {
        return vstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.vstatus
     *
     * @param vstatus the value for vipuser.vstatus
     *
     * @mbg.generated
     */
    public void setVstatus(String vstatus) {
        this.vstatus = vstatus == null ? null : vstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.createtime
     *
     * @return the value of vipuser.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.createtime
     *
     * @param createtime the value for vipuser.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.updatetime
     *
     * @return the value of vipuser.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.updatetime
     *
     * @param updatetime the value for vipuser.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipuser.is_parent
     *
     * @return the value of vipuser.is_parent
     *
     * @mbg.generated
     */
    public String getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipuser.is_parent
     *
     * @param isParent the value for vipuser.is_parent
     *
     * @mbg.generated
     */
    public void setIsParent(String isParent) {
        this.isParent = isParent == null ? null : isParent.trim();
    }
}